### ISSUE TITLE
Move this repo to php-gettext

### ISSUE THREAD

**Issue by oscarotero** [php-gettext/Languages#24]
Hi!
I've created the php-gettext organization (https://github.com/php-gettext) and moved all packages related with gettext to there. The new version 5.0 also splits the whole repository in small packages (translator, scanner, etc), so developers can install only those features that really need.

Because this package is a dependency that uses the same vendor and namespace, I'm wonder if you're interested in move it to the organization, under the `php-gettext/languages` repository. You would still be the maintainer. What do you think?

**Comment by mlocati** [comment]
Hi Oscar!

Yep, that would be a better structure. BTW, what about the existing projects pointing to `mlocati/cldr-to-gettext-plural-rules`? Is there any way to "redirect" or "forward" users to `php-gettext/languages`? Or should I simply leave this `mlocati/cldr-to-gettext-plural-rules` somehow *abandoned*?

**Comment by oscarotero** [comment]
Github redirects automatically the projects renamed or/and moved. For example, the old url of gettext package https://github.com/oscarotero/Gettext is redirected automatically to the new one https://github.com/php-gettext/Gettext

**Comment by mlocati** [comment]
Great: I also noticed that cloning https://github.com/oscarotero/Gettext.git still works.

So, how to proceed? Should I use the "Transfer ownership" function of https://github.com/mlocati/cldr-to-gettext-plural-rules/settings ?

**Comment by mlocati** [comment]
And PS: I'd rename it to https://github.com/php-gettext/Languages

**Comment by oscarotero** [comment]
Yes, exactly. I'm also sending you an invitation to join to the php-gettext team.

**Comment by mlocati** [comment]
Done :wink:

**Comment by oscarotero** [comment]
Welcome!

**Comment by mlocati** [comment]
I don't have access to the settings of this repository. Could you grant me admin rights on it?

**Comment by mlocati** [comment]
Thanks!
