### ISSUE TITLE
CLDR 37 and

### ISSUE THREAD

**Issue by doublex** [php-gettext/Languages#31]
Hello,

Would it be possible to update to CLDR 37?

And GCC complains a warning: suggest parentheses around ‘&&’ within ‘||’
E.g.:
````
{
  "name": "Romanian",
  "formula": "(n == 1) ? 0 : ((n == 0 || n % 100 >= 2 && n % 100 <= 19) ? 1 : 2)",
}
````

Thanks a lot for this great module
Best wishes

**Comment by mlocati** [comment]
Done: this library now uses CLDR 39.
Versus the previous CLDR 36 data, we have these new languages:

- `doi` (Dogri)
- `lij` (Ligurian)
- `pcm` (Nigerian Pidgin)
- `sat` (Santali)

I'll publish a new release app.

For the GCC issue, could you open a new issue?

**Comment by doublex** [comment]
@mlocati 
Thank you for the effort!

**Comment by mlocati** [comment]
(Sorry for the unacceptable delay)

**Comment by doublex** [comment]
Not that much has changed ... 
Great code!

**Comment by mlocati** [comment]
Well, the major change is that French now has 3 plural forms (for example for "1 million"): see https://github.com/php-gettext/Languages/commit/798a8cc0c7750aaa9f433e81fe4a2e621ca5ad3e
