### ISSUE TITLE
There is an incorrect plural form for French.

### ISSUE THREAD

**Issue by Sendey7** [php-gettext/Languages#42]
Hi!
I found out that the library returns 3 plural forms for the French language - https://php-gettext.github.io/Languages/ (http://i.imgur.com/8sjFFM6.png). This is a screenshot from my debug code - http://i.imgur.com/L4GEBXs.png
But other sources say that there are only two plural forms:
- http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms (http://i.imgur.com/Kq8OvXp.png)
- https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html (http://i.imgur.com/lV6zUnT.png)
- Poedit - http://i.imgur.com/3Lp0SoB.png , http://i.imgur.com/rsMoaX9.png

Could you please help me with this?

Thanks!

**Comment by mlocati** [comment]
That's correct: the third plural form for French has been introduced in the Unicode CLDR data (it's the source of the data of php-gettext/Languages): see https://cldr.unicode.org/index/downloads/cldr-38#h.7ahoxbsngtxp

This third plural category is used to translate the multiple of millions.

For example

| English | French |
|---|---|
| 1 view | 1 vue |
| 2 views | 1 vues |
| 1.000.000 views | 1.000.000 de vues (read as "1 million de vues") |

That's not my choice: Unicode people switched to that approach...

**Comment by Sendey7** [comment]
@mlocati
Thank you for the explanation!
