### ISSUE TITLE
be, pl, uk - missing plural rule for "many"

### ISSUE THREAD

**Issue by seeden** [php-gettext/Languages#48]
Hi, 

Thanks for nice package.
I see that generated plural rules and categories are ignoring "many" for be,pl,uk locales.

Here is example of CLDR 44:
```json
      "pl": {
        "pluralRule-count-one": "i = 1 and v = 0 @integer 1",
        "pluralRule-count-few": "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …",
        "pluralRule-count-many": "v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …",
        "pluralRule-count-other": "   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …"
      },

```

output is just one, few, other which is not compatible.
Can you help me to fix it?

Thank you

**Comment by mlocati** [comment]
Is the fourth case only for non integer numbers?
If so: gettext only supports integer numbers

**Comment by seeden** [comment]
yeah, I know.
I am using only your plural rule (formulas) for creating of PO files.
Is there any chance to add support for decimals as well? 
If no, I totally understand it and I will do it in different way without this library.

**Comment by mlocati** [comment]
It's not possible: gettext only supports integers

**Comment by seeden** [comment]
yeah I know but I need it for something else with decimals as well

**Comment by mlocati** [comment]
` ¯\_(ツ)_/¯ ` there's nothing I can do...
